### ISSUE TITLE
Data build process

### ISSUE THREAD

**Issue by eamonjohnson** [opencleveland/large-lots#13]
Need to figure out how to consistently refresh the site with most current data from the City of Cleveland Land Bank site.

**Comment by cwang912** [comment]
Is there a way to get a csv or json of the available stuff through NST? I've looked at the NST User Guide, and it's not in there as far as I can tell (although the normal user is not looking for this type of functionality).

**Comment by eamonjohnson** [comment]
The data dictionary at
http://neocando.case.edu/nst/DataService?function=data-dictionary is an
HTML version of the available categories and fields.

**Comment by cwang912** [comment]
SHUT IT DOWN, WE'RE DOING IT MANUALLY!
