### ISSUE TITLE
Production environment

### ISSUE THREAD

**Issue by eamonjohnson** [opencleveland/large-lots#14]
Need to arrange production hosting.  Possible directions include (1) subsite of existing largelots.org, and (2) hosting funded by local government, foundation, or other NGO.

**Comment by pkoepke** [comment]
Current plan: leave the app on an AWS instance managed by Open Cleveland, funded by a local NGO. I believe someone (Carter?) has already found someone to provide the funds. Shouldn't cost more than $40/month.

I own clelots.org and clevelandlots.org so I could transfer them to Open Cleveland when we're ready to go.

**Comment by cwang912** [comment]
Tangentially related to the previous conversation, but I believe I got an update of the code that was working in development into production, however now upon submission of an application, the site returns a 504 error instead of successfully reaching a confirmation page.
