### ISSUE TITLE
Document data process

### ISSUE THREAD

**Issue by cwang912** [opencleveland/large-lots#23]
* log into [NST](www.neocando.com/nst/) with username opencleveland@gmail.com. Get the password in the Large-Lots Slack channel
* Click "Cleveland city" to navigate to the data 
* Click "Reports" on the menu bar, and then select "Municipal lots w/sqft"
* Click "Download" on the menu bar, and then click "data download".
* The downloaded csv will have a messy name rename it to downloaded.csv or something.
* Rename "GIS Area (sq ft)" as "sqft"
* Acquire the parcels.csv -- a csv that contains the parcel boundaries. Carter has a copy, as well as one being on the brigade's [Socrata portal](https://brigades.opendatanetwork.com/catalog?Brigade_Group=Open%20Cleveland). That has it in a shapefile format, conversion is possible with ogr2ogr.
* If both files are in the same folder and you have [csvkit](https://csvkit.readthedocs.org/en/0.9.1/) installed, run ```csvjoin -c "column1, column2" downloaded.csv parcels.csv > joined.csv```, where column1 and column2 are the indices associated with the the columns that are being joined in the two csvs. It should be "1,3"
* Upload joined.csv into [CartoDB](https://opencleveland.cartodb.com/tables/joined/table) -- note that you have to **delete the old copy of joined.csv first** since the name of the dataset is what is accessed in the javascript files (largelots_cleveland.js or largelots_admin.js). The username for this is also opencleveland@gmail.com and the password is also in the Large-Lots Slack channel

ISSUE: csvjoin considers the ppn to be a number and removes leading 0's! Don't want that behavior, want it to be a string! -- doesn't matter -- use the full parcel number

**Comment by cwang912** [comment]
To put quotations marks around the ppn to ensure things are interpreted as strings instead of numbers, use:

sed -e 's/,\([0-9]\{8\}[a-z]\{0,1\}\),/,\"\1\",/g' FILENAME

THIS WON'T WORK ON A WINDOWS MACHINE IF YOU DON'T HAVE SOMETHING INSTALLED (i.e. cygwin)

**Comment by cwang912** [comment]
Rename GIS Area (sq ft) to sqft manually

**Comment by pkoepke** [comment]
Thank you for documenting this. Question: "Download municipal land up for grabs in NST -- click data download." What's the address of the NST site? And once we're logged in to NST, how do we reach the page with the municipal land for sale? I know we can't post NST credentials can we give enough detail so someone with those credentials but no knowledge of NST could do the download?

**Comment by cwang912** [comment]
I'll do this -- not sure what the best solution is to the password for NST,
but we can work around that certainly.

**Comment by pkoepke** [comment]
What's the NST site's URL?

**Comment by pkoepke** [comment]
Never mind, the NST site URL is http://neocando.case.edu/nst/index.jsp.

**Comment by cwang912** [comment]
I guess -- they report http://neocando.case.edu/nst/
