### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/large-lots#26]
Update README For the Cleveland context; 

could include basic steps for forking/reproduction; and also a few sentences of what the project does.

**Comment by skorasaurus** [comment]
I did a first revision in https://github.com/opencleveland/large-lots/commit/fe3c5d860ae651473ae99aa40a039a0a97a26efe 

If someone else could verify its information and add anything else that would be super.

**Comment by pkoepke** [comment]
This has mostly been updated. The only glaring deficiency is it doesn't describe how to set up PostgreSQL if you're building the server from scratch. Feel free to suggest other edits.

I'm also unsure if we are supposed to add ourselves to the copyright, add a new copyright, or leave it as-is. Regardless the original code is MIT license so I believe we should leave the license alone.

**Comment by pkoepke** [comment]
Consider adding "how to pull new code from the master branch into the production environment."

**Comment by skorasaurus** [comment]
@pkoepke ; think the edits that have been done in 2015 are sufficient for now;
