### ISSUE TITLE
Apply page loses details when an error is found

### ISSUE THREAD

**Issue by pkoepke** [opencleveland/large-lots#29]
If the user fills out the form on the Apply page and submits the application, but there's a problem (e.g., an unsupported file type), the following fields' information is lost:
- Lot improvements "Verify whether or not you have made improvements to the lot"
- Owned property status "Provide information on the current residents of the property"
- Owned properties "Provide information on whether or not you own multiple properties in Cleveland"
- File to upload for the Plan

There may be other not-required fields that are lost.

It would be ideal to keep all the information the user has entered so they don't have to reenter it. Also, since a user would typically expect the form to remember what they entered, the user is likely to miss a required field again.

**Comment by pkoepke** [comment]
Quick note: this is not a go live critical issue, so we can fix it after the critical issues are handled.

**Comment by skorasaurus** [comment]
fixed in https://github.com/opencleveland/large-lots/commit/a9050b82b8e61fc0ac2709f23ed56508f9595164
