### ISSUE TITLE
Sending applications to the Cleveland Land Bank

### ISSUE THREAD

**Issue by cwang912** [opencleveland/large-lots#3]
Have to make sure that it's emailed to the right person -- how is it emailed? Are we also storing the submissions in a machine readable format? How do we do this with pictures?

Might have to create multiple issues for this. Please add.

**Comment by pkoepke** [comment]
As far as sending emails goes, the folks in Chicago just created a Gmail account to send from. Email volume is expected to be low. But we probably want to store the info in a DB permanently so it doesn't exist only in email format.

**Comment by pkoepke** [comment]
@arielkoiman Ariel - are the emails working now? Where in the code is this done so we know where to turn it on / off?

**Comment by arielkoiman** [comment]
Yeah, the emails are good to go. Here's the code in lots_client\views.py:

![capture](https://cloud.githubusercontent.com/assets/6097369/8414274/f73e44ee-1e64-11e5-96fc-95c93be848e6.PNG)

The server and port info are all in local_settings.

**Comment by pkoepke** [comment]
Thanks! Looks great. So is this sending emails today from our server? Or is it missing the email to send to?

**Comment by arielkoiman** [comment]
It gets the destination email from the application. It should still be working--I just had it send you a confirmation email to test.
