### ISSUE TITLE
Map of lots disappeared from production site in 11/2015

### ISSUE THREAD

**Issue by pkoepke** [opencleveland/large-lots#36]
A month ago or so I noticed that the map of available lots on the production site (www.clelots.org or www.clevelandlots.org) disappeared. I'm not sure why it would disappear - I don't see any commits around that time (except the FAQ update on 12/4), but someone could have gone in to /home/ubuntu/ and made changes manually.

It's possible that the map itself disappeared from the external site where it's hosted.

**Comment by skorasaurus** [comment]
no longer applicable
