### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/large-lots#38]
getting a 502 error when visiting clevelandlots.org :( 

likely something with our AWS instance?

**Comment by pkoepke** [comment]
Same on http://clevelandlots.org/ and http://clelots.org/

**Comment by cwang912** [comment]
Been meaning to look into that, but I don't know the cause. I can launch
the website and it stays live for a while before 502-ing at some point.

**Comment by pkoepke** [comment]
Carter, what command are you using to launch the site?

**Comment by cwang912** [comment]
`sudo bash /home/ubuntu/run_uwsgi_for_prod_lots.bash`

**Comment by pkoepke** [comment]
You want this command:

`nohup bash /home/ubuntu/run_uwsgi_for_prod_lots.bash &`

I think you can do it without `sudo`, but test it without `sudo` and see. When I log in as user `ubuntu` it works without sudo.

`nohup` - disconnects the output from your current terminal session.

`&` - runs the task as a background task.

If you run it without `nohup` or `&`, then when you close your terminal session the uwsgi process dies with your terminal, resulting in a 502 error.

**Comment by skorasaurus** [comment]
Closing this since the issue is no longer happening.
