### ISSUE TITLE
entire site is down; amazon AWS changed the IP address. 

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/large-lots#62]
I deleted some entries in the database b/c when i opened the csv of submissions they weren't
displaying properly in libreoffice; i then realized that the problem was libreoffice not prasing the csv right and when I changed the parsing options in libreoffice, csv opened it fine; 
and then realize that the problem was with libreoffice. 

Right before I realized that the problem was with libreoffice, I did a sudo shutdown -r now; 

and when I went to clevelandlots.org; I got a 'Welcome to nginx!' file; 

I thought, oh, I'll do what I normally do to bring up the server what I did: 

```
nohup bash /home/ubuntu/run_uwsgi_for_prod_lots.bash &
sudo service nginx restart
```

but I still same result (got the nginx window); FUCK

I rebooted the instance in the aws console; 

```
nohup bash /home/ubuntu/run_uwsgi_for_prod_lots.bash &
sudo service nginx restart
```

But I got a generic configuration of 

I rebooted it in the aws console; 

nohup bash /home/ubuntu/run_uwsgi_for_prod_lots.bash &
then cancelled out of the windows
sudo service nginx restart

same result (got the nginx window)

I THEN thought to stop the instance in the aws console and restart it... 
well, while it did that; it gave a whole new public IP address. smh.

**Comment by skorasaurus** [comment]
so new public ip address: 34.209.73.55

I now needed to change configuration values to a few settings becaues of the Ip change. 
I changed server_name's value in /usr/share/large-lots/create_large_lots_nginx.conf
(was 52.10.73.22) to 34.209.73.55

I then did: sudo service nginx restart
and then nohup bash /home/ubuntu/run_uwsgi_for_prod_lots.bash &

and no longer get the nginx welcome screen, but instead get a 400 error (bad request) when I visit the ip address 

i sought to see if I could load the site locally while on the server; so while in ssh, I did the following in /usr/share/large-lots 
python manage.py runserver

and then did curl localhost:8000 to see if it'd load locally; but no; still was returning 
400 bad request; 

(nice tip from https://gist.github.com/eezis/7586964)

then also reading that reminded me to edit ALLOWED_HOSTS = in local_settings.py in /usr/share/large-lots; 
and I add the public IP there ; (let's get the site working first, then worry about the )
and then did nohup bash /home/ubuntu/run_uwsgi_for_prod_lots.bash &
sudo service nginx restart
and still returned 400 bad request. :/

**Comment by saxenanurag** [comment]
You need to point the `A` record for the domain to the new public IP. You dont have to change anything in your NGINX configuration. What happened was when you rebooted, AWS gave you a new public IP address. All you have to do is change the `A` record. Let me know if this works.

**Comment by skorasaurus** [comment]
thanks to 
@saxenanurag  ; who changed updated https://github.com/opencleveland/large-lots/blob/master/large_lots_nginx.conf#L13 to have the values of clevelandlots.org and clelots.

**Comment by skorasaurus** [comment]
so the issue was, up until early 2018: that the domain was registered through amazon but the nameservers were for nearlyfreespeech.net for both clelots.org and clevelandlots.org
ns.phx5.nearlyfreespeech.net
ns.phx8.nearlyfreespeech.net (this was configured as such on our aws.amazon.com)

and then there were A records (at nearlyfreespeech.net account)that were to the 
public IP address of our AWS instance.

see image below: 
![selection_017](https://user-images.githubusercontent.com/955351/38061762-9f5cdfda-32be-11e8-91de-671cf16c9ded.png)

**Comment by skorasaurus** [comment]
first, I needed to create a hosted zone in route53 so I would be able to use amazon's nameservers (following: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/migrate-dns-domain-in-use.html) (really was helpful :)) 

(SO, I created the hosted zone which gave us our name servers and A record..
Then I updated the name servers for clevelandlots.org at https://console.aws.amazon.com/route53/home#DomainDetail:clevelandlots.org
to match what was in the hosted zone. 
and then I went to nearlyfreespeech and removed the A records and the nameservers there.

and after :) 


https://www.whatsmydns.net/#NS/clevelandlots.org 
and after: 
![selection_018](https://user-images.githubusercontent.com/955351/38062304-39347c42-32c1-11e8-87b3-4dd9af24d47c.png)

shows our nameserver pointing to amazon :)
